version: '3'
services:
  db:
    image: postgres:12.3
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file: .env   
  web:
    build: .
    image: shopify
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - rails_cache:/app/tmp/cache
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env  
    environment:
      - ENABLE_BOOTSNAP=true
  resque:
    image: shopify:latest
    command: bash -c "bundle exec rails environment resque:work QUEUE=*"
    volumes:
      - .:/app
    depends_on:
      - redis
    links:
      - smtp
    environment:
      - ENABLE_BOOTSNAP=false
  webpacker:
    image: shopify:latest
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - NODE_OPTIONS="--max_old_space_size=4096"
    command: bash -c "yarn && rm -rf /rails/public/packs && bin/webpack-dev-server"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file: .env  
    ports:
      - '3035:3035'
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  smtp:
    image: mailhog/mailhog
    ports: 
      - 1025:1025
      - 8025:8025
volumes:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs: