default: &default
  adapter: redis
  url: <%= "redis://#{ENV['REDIS_HOST']}:#{ENV['REDIS_PORT']}/1" %>

development:
  <<: *default
  channel_prefix: shopify_development

test:
  adapter: test

production:
  <<: *default
  channel_prefix: shopify_production